- name: Configure Apache with SSL and HTTP to HTTPS redirection
  hosts: webserver
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache and OpenSSL
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - openssl

    - name: Enable necessary Apache modules
      command: a2enmod ssl rewrite
      notify: Restart Apache

    - name: Generate self-signed SSL certificate
      command: openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=US/ST=State/L=City/O=Organization/CN=54.162.95.7" -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt
      args:
        creates: /etc/ssl/certs/apache-selfsigned.crt

    - name: Configure Apache for SSL and redirect HTTP to HTTPS
      copy:
        content: |
          <IfModule mod_ssl.c>
            <VirtualHost *:80>
                ServerName 54.162.95.7
                RewriteEngine On
                RewriteRule ^(.*)$ https://54.162.95.7/$1 [R=301,L]
            </VirtualHost>

            <VirtualHost *:443>
                DocumentRoot "/var/www/html"
                ServerName 54.162.95.7
                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
                SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
                <Directory "/var/www/html">
                    AllowOverride None
                    Require all granted
                </Directory>
            </VirtualHost>
          </IfModule>
        dest: /etc/apache2/sites-available/default-ssl.conf
      notify: Restart Apache

    - name: Create web content
      copy:
        content: |
          <html>
          <head>
            <title>Hello World</title>
          </head>
          <body>
            <h1>Hello World!</h1>
          </body>
          </html>
        dest: /var/www/html/index.html

    - name: Enable the SSL site
      command: a2ensite default-ssl
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- name: Validate server configuration
  hosts: webserver
  become: yes
  tasks:
    - name: Check if Apache is running
      systemd:
        name: apache2
        state: started
      register: apache_status

    - name: Assert Apache is running
      assert:
        that:
          - apache_status.status.ActiveState == 'active'

    - name: Check if SSL certificate exists
      stat:
        path: /etc/ssl/certs/apache-selfsigned.crt
      register: ssl_cert

    - name: Assert SSL certificate exists
      assert:
        that:
          - ssl_cert.stat.exists

    - name: Check if SSL key exists
      stat:
        path: /etc/ssl/private/apache-selfsigned.key
      register: ssl_key

    - name: Assert SSL key exists
      assert:
        that:
          - ssl_key.stat.exists

    - name: Check if default-ssl.conf is in place
      stat:
        path: /etc/apache2/sites-available/default-ssl.conf
      register: ssl_conf

    - name: Assert default-ssl.conf is in place
      assert:
        that:
          - ssl_conf.stat.exists

    - name: Test HTTPS connection with SSL validation disabled
      uri:
        url: https://54.162.95.7
        method: GET
        return_content: yes
        validate_certs: no
      register: https_response

    - name: Verify HTTPS content
      uri:
        url: https://54.162.95.7
        validate_certs: no
      register: https_content

    - name: Assert HTTPS content
      assert:
        that:
          - https_content.status == 200
          - "'Hello World' in https_response.content"
